### PR TITLE
MLIR: fix iv reverse map for scf.for mincut

### LINKED ISSUE #2657: Reverse mode applied to scf.for produces incorrect derivatives
I've run across what appears to be a bug while computing the adjoint for certain `scf.for` operations with reverse mode.  For example, the code below computes `z = x*y` for 1-D arrays `x`, `y`, and `z`:
```
module {
  func.func @scale(%x: memref<?xf64>, %y: memref<?xf64>, %z: memref<?xf64>) {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %dim = memref.dim %x, %c0 : memref<?xf64>
    scf.for %i = %c0 to %dim step %c1 {
      %0 = memref.load %x[%i] : memref<?xf64>
      %1 = memref.load %y[%i] : memref<?xf64>
      %2 = arith.mulf %0, %1 : f64
      memref.store %2, %z[%i] : memref<?xf64>
    }
    return
  }
  func.func @dscale(%x: memref<?xf64>, %y: memref<?xf64>, %z: memref<?xf64>, %dy: memref<?xf64>, %dz: memref<?xf64>) {
    enzyme.autodiff @scale(%x, %y, %dy, %z, %dz) { 
        activity=[#enzyme<activity enzyme_const>, #enzyme<activity enzyme_dup>, #enzyme<activity enzyme_dup>], 
        ret_activity=[] 
      } : (memref<?xf64>, memref<?xf64>, memref<?xf64>, memref<?xf64>, memref<?xf64>) -> ()
    return
  }
}
```
Differentiating this with respect to `y` treating `x` as constant with Enzyme HEAD as of today via
```
enzymemlir-opt scale_bug.mlir --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize --enzyme-simplify-math --cse
```
I get this output:
```
module {
  func.func @scale(%arg0: memref<?xf64>, %arg1: memref<?xf64>, %arg2: memref<?xf64>) {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %dim = memref.dim %arg0, %c0 : memref<?xf64>
    scf.for %arg3 = %c0 to %dim step %c1 {
      %0 = memref.load %arg0[%arg3] : memref<?xf64>
      %1 = memref.load %arg1[%arg3] : memref<?xf64>
      %2 = arith.mulf %0, %1 : f64
      memref.store %2, %arg2[%arg3] : memref<?xf64>
    }
    return
  }
  func.func @dscale(%arg0: memref<?xf64>, %arg1: memref<?xf64>, %arg2: memref<?xf64>, %arg3: memref<?xf64>, %arg4: memref<?xf64>) {
    call @diffescale(%arg0, %arg1, %arg3, %arg2, %arg4) : (memref<?xf64>, memref<?xf64>, memref<?xf64>, memref<?xf64>, memref<?xf64>) -> ()
    return
  }
  func.func private @diffescale(%arg0: memref<?xf64>, %arg1: memref<?xf64>, %arg2: memref<?xf64>, %arg3: memref<?xf64>, %arg4: memref<?xf64>) {
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %cst = arith.constant 0.000000e+00 : f64
    %dim = memref.dim %arg0, %c0 : memref<?xf64>
    %alloc = memref.alloc(%dim) : memref<?xf64>
    scf.for %arg5 = %c0 to %dim step %c1 {
      %0 = memref.load %arg0[%arg5] : memref<?xf64>
      memref.store %0, %alloc[%arg5] : memref<?xf64>
      %1 = memref.load %arg1[%arg5] : memref<?xf64>
      %2 = arith.mulf %0, %1 : f64
      memref.store %2, %arg3[%arg5] : memref<?xf64>
    }
    scf.for %arg5 = %c0 to %dim step %c1 {
      %0 = arith.subi %dim, %c1 : index
      %1 = arith.subi %0, %arg5 : index
      %2 = memref.load %alloc[%1] : memref<?xf64>
      %3 = memref.load %arg4[%arg5] : memref<?xf64>
      memref.store %cst, %arg4[%arg5] : memref<?xf64>
      %4 = arith.mulf %3, %2 : f64
      %5 = memref.load %arg2[%arg5] : memref<?xf64>
      %6 = arith.addf %5, %4 : f64
      memref.store %6, %arg2[%arg5] : memref<?xf64>
    }
    memref.dealloc %alloc : memref<?xf64>
    return
  }
}
```
Notice that the taped values (`%alloc`) are read in the correct reverse order, but the adjoint arrays for `dz` (`%arg4`) and `dy` (`%arg2`) are read/written in the forward order.  When fully compiled, this results in the derivatives in `dy` being in reverse order.  I believe the correct code would replace `%arg5` with `%1` in the body of the adjoint loop.

### PR DESCRIPTION
**Pull request by Pangoraw**
fixes #2657.

### CODE REVIEW

File: enzyme/Enzyme/MLIR/Implementations/SCFAutoDiffOpInterfaceImpl.cpp [hunk 1]
```diff
@@ -653,12 +658,6 @@ struct ParallelOpEnzymeOpsRemover
     }
     return bounds;
   }
-  static SmallVector<Value>
-  computeReversedIndices(PatternRewriter &rewriter, scf::ParallelOp parOp,
-                         ArrayRef<Value> otherInductionVariable,
-                         ArrayRef<IntOrValue> bounds) {
-    return SmallVector<Value>(otherInductionVariable);
```
Comment (wsmoses) [inline enzyme/Enzyme/MLIR/Implementations/SCFAutoDiffOpInterfaceImpl.cpp:660]: This shouldn't be necessary to remove?

For a parallel op we don't need to reverse the indices (as long as we're consistent)
