### PR TITLE
Fix unwrap

### LINKED ISSUE #643: Reverse vector mode stack overflow
Reverse vector mode causes a stack overflow when looking up / unwrapping values for a large vector width.

This issue seems related to the stack overflow we have seen in Julia.

https://fwd.gymni.ch/apJzvT

**note**: The above example works perfectly fine with lower vector widths.

### PR DESCRIPTION
**Pull request by tgymnich**
fixes #643

### CODE REVIEW

File: enzyme/Enzyme/GradientUtils.cpp [hunk 1]
```diff
@@ -442,22 +442,36 @@ Value *GradientUtils::unwrapM(Value *const val, IRBuilder<> &BuilderM,
...
-      unwrappedLoads[newi] = val;
-      if (newi->getParent()->getParent() != op->getParent()->getParent())
-        newi->setDebugLoc(nullptr);
+    SmallVector<std::pair<Value *, unsigned>, 0> insertElements;
+    Value *agg = op->getAggregateOperand();
+    while (auto op1 = dyn_cast<InsertValueInst>(agg)) {
+      if (knownRecomputeHeuristic.count(op1) &&
+          knownRecomputeHeuristic[op1] == true)
+        break;
+      insertElements.push_back({op1->getInsertedValueOperand(),
```
Comment (wsmoses) [inline enzyme/Enzyme/GradientUtils.cpp:451]: You should check that there's only 1 such index?

Comment (tgymnich) [reply enzyme/Enzyme/GradientUtils.cpp:451]: or maybe just assert?

Comment (wsmoses) [reply enzyme/Enzyme/GradientUtils.cpp:451]: No because there are plenty of multi-index insertions, and we would then have compilation fail when unwrapping them (ignorant of vector mode even)

Comment (tgymnich) [reply enzyme/Enzyme/GradientUtils.cpp:451]: added check

Comment (wsmoses) [reply enzyme/Enzyme/GradientUtils.cpp:451]: I don't see the check?

Comment (tgymnich) [reply enzyme/Enzyme/GradientUtils.cpp:451]: forgot to commit and push

Comment (wsmoses) [reply enzyme/Enzyme/GradientUtils.cpp:451]: Still dont see this `if (op1->getNumIndices() != 1) break` check

Comment (wsmoses) [reply enzyme/Enzyme/GradientUtils.cpp:451]: The count doesn't need to check against 1, if that's what you misunderstood this as.

File: enzyme/Enzyme/GradientUtils.cpp [hunk 2]
```diff
@@ -442,22 +442,36 @@ Value *GradientUtils::unwrapM(Value *const val, IRBuilder<> &BuilderM,
...
+                                op1->getInsertedValueOperandIndex()});
+      agg = op1->getAggregateOperand();
     }
+
+    Value *toreturn = agg;
+    for (auto &&[valOp, idcs] : reverse(insertElements)) {
+      auto op1 = getOp(valOp);
```
Comment (wsmoses) [inline enzyme/Enzyme/GradientUtils.cpp:458]: Can you also add a regular reverse mode test where the knownrecompute is somewhere in the chain, and confirm we get the intended behavior from the cache analysis?

File: enzyme/Enzyme/GradientUtils.cpp [hunk 3]
```diff
@@ -442,22 +442,38 @@ Value *GradientUtils::unwrapM(Value *const val, IRBuilder<> &BuilderM,
...
-    auto toreturn = BuilderM.CreateInsertValue(op0, op1, op->getIndices(),
-                                               op->getName() + "_unwrap");
-    if (permitCache)
-      unwrap_cache[BuilderM.GetInsertBlock()][idx.first][idx.second] = toreturn;
-    if (auto newi = dyn_cast<Instruction>(toreturn)) {
-      newi->copyIRFlags(op);
-      unwrappedLoads[newi] = val;
-      if (newi->getParent()->getParent() != op->getParent()->getParent())
-        newi->setDebugLoc(nullptr);
+    SmallVector<std::pair<Value *, unsigned>, 0> insertElements;
```
Comment (tgymnich) [inline enzyme/Enzyme/GradientUtils.cpp:445]:
```suggestion
    SmallVector<std::pair<Value *, unsigned>, 4> insertElements;
```

**Review by wsmoses — APPROVED** [review]
