### PR TITLE
Remove unused -lblas from benchmarks

### LINKED ISSUE #1102: Error running the benchmark
I am trying to run `ninja bench-enzyme` following the Installation guide. However, I got errors for all tests. The error message for one of the tests is like:

```
********************                                                                                                                                                                                                                [14/1854]FAIL: BenchEnzyme :: ReverseMode/taylorlog/Makefile.make (13 of 13)
******************** TEST 'BenchEnzyme :: ReverseMode/taylorlog/Makefile.make' FAILED ********************
Script:
--
: 'RUN: at line 1';   cd /home/rd/src/Enzyme_experiments/Enzyme/enzyme/benchmarks/ReverseMode/taylorlog && LD_LIBRARY_PATH="/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/adept2/install/lib:$LD_LIBRARY_PATH" BENCH="-I/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/adept2/src/adept2/include -I/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade" BENCHLINK="/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade/adBuffer.o /home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade/adStack.o -L/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/adept2/install/lib -ladept" LOAD=" -load=/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-12.so -enzyme-preopt=0" make -B taylorlog-raw.ll taylorlog-opt.ll results.txt VERBOSE=1 -f /home/rd/src/Enzyme_experiments/Enzyme/enzyme/benchmarks/ReverseMode/taylorlog/Makefile.make                                                                                                                                                                                                                      --                                                                                                                                                                                                                                           Exit Code: 2

Command Output (stdout):
--
clang++ -I/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/adept2/src/adept2/include -I/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade taylorlog.cpp -ffast-math -O2 -fno-unroll-loops -fno-vectorize -o taylorlog-unopt.ll -S -emit-llvm
opt taylorlog-unopt.ll  -load=/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-12.so -enzyme-preopt=0 -enzyme -mem2reg -early-cse -correlated-propagation -aggressive-instcombine -adce -loop-deletion -o taylorlog-raw.ll -S
opt taylorlog-raw.ll -O2 -o taylorlog-opt.ll -S
clang++ taylorlog-opt.ll -o taylorlog.o -lblas /home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade/adBuffer.o /home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/tapenade/src/tapenade/adStack.o -L/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/adept2/install/lib -ladept -lm
rm taylorlog-unopt.ll

--
Command Output (stderr):
--
In file included from taylorlog.cpp:17:
/home/rd/src/Enzyme_experiments/Enzyme/enzyme/build/benchmarks/adept2/src/adept2/include/adept_source.h:46:2: warning: "The adept_source.h header file has not been edited so BLAS matrix multiplication and LAPACK linear-algebra support have been disabled" [-W#warnings]
#warning "The adept_source.h header file has not been edited so BLAS matrix multiplication and LAPACK linear-algebra support have been disabled"
 ^
1 warning generated.
/home/spack/spack/opt/spack/linux-debian11-zen2/clang-13.0.1/binutils-2.38-uwxndqcv3temlw5uwctdq4htgzl3yx2j/bin/ld: cannot find -lblas: No such file or directory
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/home/rd/src/Enzyme_experiments/Enzyme/enzyme/benchmarks/ReverseMode/taylorlog/Makefile.make:18: taylorlog.o] Error 1
```

The problem seems simple: it was trying to link against BLAS, but BLAS was not found. However, I still have some questions:

1. Different BLAS libraries have different library names. It seems `-lblas` only works for OpenBLAS, but I am using MKL, so it is not found.
2. Is this error happens when we are compiling Enzyme, or when we are compiling the baseline Adept?
    a) If this is an error from Adept, I can't reproduce the error by compiling Adept manually. Adept successfully found my MKL installation. So what was going wrong?
    b) If this is an error from Enzyme (because Enzyme uses the Adept code for test?), is this a bug in the compiling script? Can Enzyme utilize BLAS? If so, I think it should be possible to link against other BLAS libraries (MKL in my case). If not, I think it should not try to link against BLAS.

### PR DESCRIPTION
**Pull request by roastduck**
Fix #1102.

### CODE REVIEW

File: enzyme/benchmarks/ReverseMode/ode/ode.cpp [hunk 1]
```diff
@@ -25,6 +25,9 @@ static float tdiff(struct timeval *start, struct timeval *end) {
 void boost::throw_exception(std::exception const & e) {
     //do nothing
 }
+void boost::throw_exception(std::exception const & e, boost::source_location const & loc) {
```
Comment (wsmoses) [inline enzyme/benchmarks/ReverseMode/ode/ode.cpp:28]: Is this needed? CI does not like it:

```cpp
Command Output (stderr):
--
ode.cpp:28:62: error: no type named 'source_location' in namespace 'boost'
void boost::throw_exception(std::exception const & e, boost::source_location const & loc) {
                                                      ~~~~~~~^
ode.cpp:28:78: error: expected ')'
void boost::throw_exception(std::exception const & e, boost::source_location const & loc) {
                                                                             ^
ode.cpp:28:28: note: to match this '('
void boost::throw_exception(std::exception const & e, boost::source_location const & loc) {
                           ^
2 errors generated.
```

**Review by wsmoses — APPROVED** [review]

File: enzyme/benchmarks/ReverseMode/ode/ode.cpp (hunk 1 above)
Comment (roastduck) [reply enzyme/benchmarks/ReverseMode/ode/ode.cpp:28]: According to [here](https://www.boost.org/doc/libs/1_81_0/libs/throw_exception/doc/html/throw_exception.html) and [here](https://www.boost.org/doc/libs/1_81_0/libs/assert/doc/html/assert.html#source_location_support),  the overload of `throw_exception` that takes a `boost::source_location` object is required since Boost 1.73.0, but `boost::source_location` is only available after Boost 1.73.0. Maybe this is the problem, and I will add a version check.
